data_dir = "./data/build"

[[repos]]
owner = "encode"
name = "httpx"
default_branch = "master"
build_command = [
    "sh",
    "-c",
    "./scripts/install && ./scripts/check && ./scripts/build && ./scripts/test && ./scripts/coverage",
]
